apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: whereami-vs
  namespace: whereami
spec:
  gateways:
  - csm-ingress/asm-ingressgateway
  hosts:
  - 'whereami.mesh.example.com'
  http:
  - route:
    - destination:
        host: whereami
        port:
          number: 80